### ISSUE TITLE
DllNotFoundException: XRSDKOpenVR

### ISSUE THREAD

**Issue by jimanjr** [ValveSoftware/unity-xr-plugin#15]
Hi,

I tried setting up a new project for VR. Went through the following steps:

- Created project using HDRP template
- Imported the XR Plugin unitypackage
- Enabled the OpenVR Loader in the Project Settings
- Made sure I'm in a scene where the Main Camera has been converted to an XRRig
- Started SteamVR just to be sure

Press Play and this error pops up. I can see the DLL in the Package Cache just fine.

`
DllNotFoundException: XRSDKOpenVR
Unity.XR.OpenVR.OpenVRLoader.Initialize () (at Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.6/Runtime/OpenVRLoader.cs:183)
UnityEngine.XR.Management.XRManagerSettings.InitializeLoaderSync () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRManagerSettings.cs:169)
UnityEngine.XR.Management.XRGeneralSettings.InitXRSDK () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:175)
UnityEngine.XR.Management.XRGeneralSettings.AttemptInitializeXRSDKOnLoad () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:148)
`
I've tried this in both 2019.4 and 2020.1 and both have the same error. I'm using Valve Index and version 1.0.0-preview.6 of the OpenVR XR Plugin

**Comment by cdytoby** [comment]
Happens to me too. Also tried not using the package manager by copying all the files into local Asset, but as soon as I clicked "openvr loader" in xrmanagement, the whole package will still be downloaded in package manager and make everything doubled.

**Comment by zite** [comment]
That's strange, I'm unable to replicate this locally using 2019.4.4f1. Can you send me a SteamVR System report (SteamVR Menu -> Create System Report -> Save to file) and the full unity editor log ( %localappdata%\Unity\Editor\Editor.log )? 

Also, just to give you a heads up - the XR Interaction system won't fully work with this plugin since it doesn't provide input. You'll need to use the SteamVR Unity Plugin for input ( https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b3 )

**Comment by jimanjr** [comment]
[SteamVR-2020-07-21-AM_07_45_25.txt](https://github.com/ValveSoftware/unity-xr-plugin/files/4951363/SteamVR-2020-07-21-AM_07_45_25.txt)
[Editor.log](https://github.com/ValveSoftware/unity-xr-plugin/files/4951364/Editor.log)

Here you go. Those are generated from 2020.1.

I also know about the interaction but when I import the SteamVR one it doesn't even compile anymore because of some missing function (ResetZeroPose or something similar). At this point, I'm just trying to see if my custom shaders work properly in VR

**Comment by cdytoby** [comment]
What? I have this issue in 2019.4.4. I'm using package manager to install this.

There are a lot of errors and warnings all due to meta file exist or not, and folder is mutable.

**Comment by jimanjr** [comment]
Oh yes I forgot to mention that there's an error that the .ilk file is missing a .meta and since it's in "PackageCache" it can't be created and the ilk is ignored. Might be related

**Comment by halfpasttense** [comment]
> Also, just to give you a heads up - the XR Interaction system won't fully work with this plugin since it doesn't provide input. You'll need to use the SteamVR Unity Plugin for input ( https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b3 )

Can you please give us an idea of when it will support XR Interaction system again? A previous version supported it and I started using it. Now that it's gone again I need to decide whether to take the time to go back again to the old way of doing input. This has really thrown a wrench in my development plans and having no idea when it will be supported again is making it pretty damn difficult to plan ahead.

**Comment by zite** [comment]
> > Also, just to give you a heads up - the XR Interaction system won't fully work with this plugin since it doesn't provide input. You'll need to use the SteamVR Unity Plugin for input ( https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b3 )
> 
> Can you please give us an idea of when it will support XR Interaction system again? A previous version supported it and I started using it. Now that it's gone again I need to decide whether to take the time to go back again to the old way of doing input. This has really thrown a wrench in my development plans and having no idea when it will be supported again is making it pretty damn difficult to plan ahead.

I'm sorry this has effected your workflow, as this package is still in beta we've decided to focus on working on OpenXR for input instead of OpenVR. We do not plan to support the XR Interaction system with this plugin.

**Comment by zite** [comment]
> Oh yes I forgot to mention that there's an error that the .ilk file is missing a .meta and since it's in "PackageCache" it can't be created and the ilk is ignored. Might be related

We may have fixed the issue with preview-7 I pushed just now. Can you update to that, give it a test, and let me know? 
Also the SteamVR Unity Plugin should compile as long as you use the beta I linked above.

**Comment by kendrome** [comment]
I'm having the same issue with preview-7 on Unity 2020.1.0b16
`DllNotFoundException: XRSDKOpenVR
Unity.XR.OpenVR.OpenVRLoader.Initialize () (at Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.7/Runtime/OpenVRLoader.cs:183)
UnityEngine.XR.Management.XRManagerSettings.InitializeLoaderSync () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRManagerSettings.cs:169)
UnityEngine.XR.Management.XRGeneralSettings.InitXRSDK () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:175)
UnityEngine.XR.Management.XRGeneralSettings.AttemptInitializeXRSDKOnLoad () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:148)`

**Comment by halfpasttense** [comment]
> I'm sorry this has effected your workflow, as this package is still in beta we've decided to focus on working on OpenXR for input instead of OpenVR. We do not plan to support the XR Interaction system with this plugin.

I'm afraid I don't quite understand. I thought OpenXR for input is the XR Interaction system. Now you're saying you're working on OpenXR for input, but then tell us to use the old OpenVR plugin for input instead? I'm thoroughly confused by all these names that have both OpenVR and XR in them. I just want to be able to use UnityEngine.XR.InputDevice.TryGetFeatureValue for getting input from Index controllers. Are you saying that won't ever be possible? Or at least not anytime soon?

**Comment by jimanjr** [comment]
> We may have fixed the issue with preview-7 I pushed just now. Can you update to that, give it a test, and let me know?
> Also the SteamVR Unity Plugin should compile as long as you use the beta I linked above.

While it seems to have fixed the issue with the missing meta, the previous issue is still there:
`DllNotFoundException: XRSDKOpenVR
Unity.XR.OpenVR.OpenVRLoader.Initialize () (at Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.7/Runtime/OpenVRLoader.cs:183)
UnityEngine.XR.Management.XRManagerSettings.InitializeLoaderSync () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRManagerSettings.cs:169)
UnityEngine.XR.Management.XRGeneralSettings.InitXRSDK () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:175)
UnityEngine.XR.Management.XRGeneralSettings.AttemptInitializeXRSDKOnLoad () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:148)`

**Comment by one1note** [comment]
I am also struggling with the above, any update?

**Comment by cdytoby** [comment]
DLL not found Exception still exist in Preview 7.

I'm glad that all warnings are gone.

I also tested by removing the package and reinstall the package, issue persists.

**Comment by one1note** [comment]
The issue is caused by commit 0dceb8aa7c42074c9efffb535ad7475f10f55aca. All the dlls were changed from Release to Debug mode. Debug dlls require the ucrtbased.dll which is missing. So a quick temporary solution would be to add the dll's manually to `Your Project File\Library\PackageCache\com.valvesoftware.unity.openvr@1.0.0-preview.7\Runtime\x86 and x64.`

You can find the dll under  `C:\Program Files (x86)\Windows Kits\10\bin\x86\ucrt\ucrtbased.dll` and if you don't have the Windows SDK, try `https://www.dll-files.com/ucrtbased.dll.html`

Restart your project and the DllNotFoundException: XRSDKOpenVR error should be resolved.

Another solution would be to build the dlls in release mode.  See https://github.com/ValveSoftware/unity-xr-plugin/blob/master/README.md#building-from-source

**Comment by Guilhem-Pech** [comment]
I've the same issue (I'm on 2020.1) !
I've tried your fix @one1note but, as soon as I had the dll on the folder, Unity invalidate the package and remove it so .... I can't do this quick fix

**Comment by matejdubec** [comment]
I am having the same issue with preview-7 on 2019.3.15

**Comment by zite** [comment]
Thanks for the heads up @one1note, I've added the debug dlls to the build. Give preview-8 a try everyone

**Comment by StefanJanssen95** [comment]
For me it seems the error is still there:
```
DllNotFoundException: XRSDKOpenVR
Unity.XR.OpenVR.OpenVRLoader.Initialize () (at Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.8/Runtime/OpenVRLoader.cs:183)
UnityEngine.XR.Management.XRManagerSettings.InitializeLoaderSync () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRManagerSettings.cs:169)
UnityEngine.XR.Management.XRGeneralSettings.InitXRSDK () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:175)
UnityEngine.XR.Management.XRGeneralSettings.AttemptInitializeXRSDKOnLoad () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:148)
```

**Comment by zite** [comment]
I'd like to try a local package before making another build. Can someone try removing the package from the package manager and then installing by hitting the plus in package manager and "install from disk..." and point it to the package.json in this zip (after extracting)
https://drive.google.com/file/d/1Zs53oegYrLzfuJw9AAcu2ovJNXAn_Rsh/

**Comment by zite** [comment]
I was able to replicate (and fix) this locally by uninstalling visual studio and some tools. Looks like we've fixed it now by compiling with static linking. Check our preview-9 and let me know if that fixes things.

**Comment by Derewen** [comment]
preview-9 fixed the issue for me, thank you!

**Comment by kendrome** [comment]
Confirmed, working me also

**Comment by zite** [comment]
Thanks for the help debugging everyone!

**Comment by guiglass** [comment]
I am getting same error but I have installed preview-12, I have also installed preview-9 but got same error.

What else could cause this missing .dll? I am using Unity 2019.3.9f1

**Comment by happysmash27** [comment]
I appear to be getting this error with the SteamVR package 2.7.3, and the thread seems to have no useful fixes :/ .

**Comment by kenontherocks** [comment]
Had a similar issue. Make sure you don't have an old version of the OpenVR package.
This is what I'm using in the packages/manifest.json:
    "com.unity.xr.interaction.toolkit": "1.0.0-pre.3",
    "com.unity.xr.management": "4.0.6",
    "com.valvesoftware.unity.openvr": "file:H:/Unity Projects/com.valvesoftware.unity.openvr-1.1.4.tgz",

I added OpenVR via the git download package and added it to Unity package manager via tarball and removed the other OpenVR package that I found in Package Manager -> Packages: In Project -> OpenVR Loader

**Comment by stellaloveslinux** [comment]
GET READY FOR BLOOD JMAN.

**Comment by stellaloveslinux** [comment]
Same issue.
OS: Blood Jmanian
Kernel: CannonBePrepared

Help?
