### ISSUE TITLE
Can't build for iOS if OpenVR XR plugin is in project

### ISSUE THREAD

**Issue by robinnorth** [ValveSoftware/unity-xr-plugin#33]
I am experiencing a similar issue to #5 when building a project for iOS (testing a combined XR and AR setup) where Unity attempts to include multiple versions of the OpenVR XR plugin's native plugins in the build, resulting in the iOS build failing:

```
Plugin 'XRSDKOpenVR.dll' is used from several locations:
 Packages/com.valvesoftware.unity.openvr/Runtime/x64/XRSDKOpenVR.dll would be copied to <PluginPath>/XRSDKOpenVR.dll
 Packages/com.valvesoftware.unity.openvr/Runtime/x86/XRSDKOpenVR.dll would be copied to <PluginPath>/XRSDKOpenVR.dll
Plugin 'openvr_api.dll' is used from several locations:
 Packages/com.valvesoftware.unity.openvr/Runtime/x86/openvr_api.dll would be copied to <PluginPath>/openvr_api.dll
 Packages/com.valvesoftware.unity.openvr/Runtime/x64/openvr_api.dll would be copied to <PluginPath>/openvr_api.dll
Plugin 'ucrtbased.dll' is used from several locations:
 Packages/com.valvesoftware.unity.openvr/Runtime/x64/ucrtbased.dll would be copied to <PluginPath>/ucrtbased.dll
 Packages/com.valvesoftware.unity.openvr/Runtime/x86/ucrtbased.dll would be copied to <PluginPath>/ucrtbased.dll
Plugin 'libopenvr_api.so' is used from several locations:
 Packages/com.valvesoftware.unity.openvr/Runtime/x64/lib/x64/libopenvr_api.so would be copied to <PluginPath>/libopenvr_api.so
 Packages/com.valvesoftware.unity.openvr/Runtime/x64/libopenvr_api.so would be copied to <PluginPath>/libopenvr_api.so
Please fix plugin settings and try again.
```

Can these native plugins have their import settings changed to only be included for Editor and Standalone platforms in the same way that the Oculus XR plugin does in order to prevent them being needlessly included in builds for unsupported platforms, like iOS?

Current OpenVR native plugin import settings:
![image](https://user-images.githubusercontent.com/3787255/89901437-fa7cea80-dbdc-11ea-892d-660119e5b3bb.png)

Oculus XR plugin import settings:
![image](https://user-images.githubusercontent.com/3787255/89901394-edf89200-dbdc-11ea-8bf2-8b27fa181df9.png)

**Comment by rpavlik** [comment]
I think I fixed this is #55 if it gets merged

**Comment by zite** [comment]
Yup, this should be fixed in the latest release. You're welcome to give it a try and let us know if it solves the problem.
https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.1b

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by mastayb** [comment]
This issue 
> `Plugin 'libopenvr_api.so' is used from several locations:
 Packages/com.valvesoftware.unity.openvr/Runtime/x64/lib/x64/libopenvr_api.so would be copied to <PluginPath>/libopenvr_api.so
 Packages/com.valvesoftware.unity.openvr/Runtime/x64/libopenvr_api.so would be copied to <PluginPath>/libopenvr_api.so
Please fix plugin settings and try again.`

Still exists in 1.1.4 for Standalone OSX and Linux builds
